---
- hosts: server-01
  become: yes
  become_user: root
  tasks:
  

  - name: install nfs
    yum:
      name: "nginx"
  - name: Start services
    service: 
      name: "nginx"
      state: started

  - name: copy forward
    template:
      src: '{{ item.source }}'
      dest: '{{ item.destination }}'
      owner: root
      group: root
      mode: "0755"
    loop:
    - { source: 'template/mynet-116.conf.j2', destination: '/etc/nginx/conf.d/mynet-116.conf' }
    - { source: 'template/my-site.conf.j2', destination: '/etc/nginx/conf.d/my-site.conf' }

  - name: reStart services
    service: 
      name: "nginx"
      state: restarted