---
- hosts: web
  become: yes
  become_user: root
  tasks:
  - name: Install remi repo.
    yum:
      name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
      state: present

  - name: Import remi GPG key.
    rpm_key:
      key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
      state: present
  
  #- name: enable repo
   # lineinfile:
    #  path: /etc/yum.repos.d/remi-php73.repo
     # regexp: 'enabled=0'
      #line: 'enabled=1'
  

  - name: install php and other 
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - php 
      - php-cli 
      - php-fpm 
      - php-mysqlnd 
      - php-zip 
      - php-devel 
      - php-gd 
      - php-mcrypt 
      - php-mbstring 
      - php-curl 
      - php-xml 
      - php-pear 
      - php-bcmath 
      - php-json

 # - name: config timezone
   # lineinfile:
    #  path: /etc/php.ini
    #  regexp: '^;date.timezone ='
    #  line: 'date.timezone = Asia/Bangkok'
  - name: create dir log 
    file:
      path: /var/www/mynet-116.com/log
      state: directory
      mode: "0755"
  - name: create dir 
    file:
      path: /var/www/mynet-116.com/html
      state: directory
      mode: "0755"
  - name: create dir 
    file:
      path: /var/www/my-site.com/html
      state: directory
      mode: "0755"
  - name: create dir 
    file:
      path: /var/www/my-site.com/log
      state: directory
      mode: "0755"
  - name: change permission
    file:
      path: /var/www
      owner: root
      group: root
      mode: "0755"
  - name: copy forward
    template:
      src: '{{ item.source }}'
      dest: '{{ item.destination }}'
      owner: root
      group: root
      mode: "0755"
    loop:
    - { source: 'template/mynet-116.com.conf.j2', destination: '/etc/httpd/conf.d/mynet-116.com.conf' }
    - { source: 'template/my-site.com.conf.j2', destination: '/etc/httpd/conf.d/my-site.com.conf' }
    - { source: 'template/1index.php.j2', destination: '/var/nfs/www/mynet-116.com/html/index.php' }
    - { source: 'template/2index.php.j2', destination: '/var/nfs/www/my-site.com/html/index.php' }
- hosts: server-03
  become: yes
  become_user: root
  tasks:
 # - name: edit1
  #  lineinfile:
  #    path: /etc/httpd/conf.d/mynet-116.com.conf
   #   regexp: 'ServerName web-02.mynet-116.com'
  #    line: 'ServerName web-02.mynet-116.com'
 # - name: edit2
  #  lineinfile:
   #   path: /etc/httpd/conf.d/my-site.com.conf
   #   regexp: 'ServerName web-02.my-site.com'
   #   line: 'ServerName web-02.my-site.com'
  #- name: edit php net
  #  lineinfile:
  #    path: /var/www/mynet-116.com/html/index.php
   #   regexp: '<?php'
   #   line: '<?php echo "web-02.mynet-116.com"; ?>'
  #- name: edit php site
   # lineinfile:
    #  path: /var/www/my-site.com/html/index.php
     # regexp: '<?php'
     # line: '<?php echo "web-02.my-site.com"; ?>'
- hosts: web
  become: yes
  become_user: root
  tasks:
  - name: enable httpd
    service:
      name: httpd
      enabled: yes

  - name: Start httpd
    service: 
      name: httpd
      state: started

  - name: enable firewalld
    service:
      name: firewalld
      enabled: yes

  - name: Start firewalld
    service: 
      name: firewalld
      state: started
    
  - name: open port 
    firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled
  
  - name: enable http
    firewalld:
      zone: public
      service: http
      permanent: yes
      state: enabled
  - name: enable https
    firewalld:
      zone: public
      service: https
      permanent: yes
      state: enabled

  - name: restart firewalld
    service: 
      name: firewalld
      state: restarted