---
- hosts: web
  become: yes
  become_user: root
  tasks:
  - name: Install remi repo.
    yum:
      name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
      state: present

  - name: Import remi GPG key.
    rpm_key:
      key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
      state: present
  
 # - name: enable repo
  #  lineinfile:
  #    path: /etc/yum.repos.d/remi-php73.repo
   #   regexp: 'enabled=0'
   #   line: 'enabled=1'
  

  - name: install php and other 
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - php 
      - php-cli 
      - php-fpm 
      - php-mysqlnd 
      - php-zip 
      - php-devel 
      - php-gd 
      - php-mcrypt 
      - php-mbstring 
      - php-curl 
      - php-xml 
      - php-pear 
      - php-bcmath 
      - php-json

#  - name: config timezone
 #   lineinfile:
  #    path: /etc/php.ini
  #    regexp: '^;date.timezone ='
   #   line: 'date.timezone = Asia/Bangkok'

  - name: enable httpd
    service:
      name: httpd
      enabled: yes

  - name: Start httpd
    service: 
      name: httpd
      state: started

  - name: enable firewalld
    service:
      name: firewalld
      enabled: yes

  - name: Start firewalld
    service: 
      name: firewalld
      state: started
    
  - name: open port 
    firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled
  
  - name: enable http
    firewalld:
      zone: public
      service: http
      permanent: yes
      state: enabled
  - name: enable https
    firewalld:
      zone: public
      service: https
      permanent: yes
      state: enabled

  - name: restart firewalld
    service: 
      name: firewalld
      state: restarted
    

  - name: copy forward
    template:
      src: '{{ item.source }}'
      dest: '{{ item.destination }}'
      owner: root
      group: root
      mode: "0755"
    loop:
    - { source: 'template/index.phpx', destination: '/var/www/html/index.php' }

- hosts: db
  become: yes
  become_user: root
  tasks:
    
  - name: install php and other 
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - mariadb-server
    

  - name: enable mariadb
    service:
      name: mariadb
      enabled: yes
    

  - name: start mariadb
    service: 
      name: mariadb
      state: started
    
  
  - name: enable firewalld
    service:
      name: firewalld
      enabled: yes
    

  - name: Start firewalld
    service: 
      name: firewalld
      state: started
    
  
  - name: open port 
    firewalld:
      port: 3306/tcp
      permanent: yes
      state: enabled
  - name: reStart firewalld
    service: 
      name: firewalld
      state: restarted
    
  
